"""Regenerate frontend/src/lib/data/dataset.generated.ts from the dataset files.

Run from the repo root after the dataset manifest, rights manifests or source registry change:

    python scripts/sync_frontend_data.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "frontend" / "src" / "lib" / "data" / "dataset.generated.ts"


def read_sources(path: Path) -> list[dict]:
    """Tiny parser for the flat `sources:` list in sources.yaml (avoids a PyYAML dependency)."""
    items: list[dict] = []
    cur: dict | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"\s*-\s+id:\s*(.+)$", line)
        if m:
            cur = {"id": m.group(1).strip().strip('"')}
            items.append(cur)
            continue
        m = re.match(r"\s+(\w+):\s*(.+)$", line)
        if m and cur is not None:
            cur[m.group(1)] = m.group(2).strip().strip('"')
    return items


def main() -> None:
    manifest = ROOT / "datasets" / "manifests" / "dataset_v1.jsonl"
    rows = [json.loads(l) for l in manifest.read_text(encoding="utf-8").splitlines() if l.strip()]
    variants = [[r["id"], r["transcript_id"], r["speaker_id"], r["flaw_type"], r["severity"], r["split"]] for r in rows]

    rights = []
    for p in sorted((ROOT / "datasets" / "rights").glob("*.json")):
        d = json.loads(p.read_text(encoding="utf-8"))
        rights.append(
            {
                "asset_id": d.get("asset_id"),
                "title": d.get("title"),
                "provider": d.get("provider"),
                "speaker": d.get("speaker"),
                "license": d.get("license"),
                "redistribution": bool(d.get("redistribution_allowed")),
                "checksum": d.get("checksum"),
                "url": d.get("canonical_url"),
            }
        )

    sources = read_sources(ROOT / "datasets" / "registry" / "sources.yaml")
    audio_files = sum(
        1 for p in (ROOT / "datasets").rglob("*") if p.suffix.lower() in {".wav", ".flac", ".mp3", ".ogg", ".m4a"}
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/sync_frontend_data.py. Do not edit by hand.\n"
        f"// Source: datasets/manifests/dataset_v1.jsonl ({len(rows)} rows), datasets/rights/*.json, "
        "datasets/registry/sources.yaml\n\n"
        "export type VariantRow = [id: string, transcript: string, speaker: string, flaw: string, severity: number, split: string]\n\n"
        f"export const VARIANTS: VariantRow[] = {json.dumps(variants, separators=(',', ':'))}\n\n"
        f"export const RIGHTS = {json.dumps(rights, indent=2)}\n\n"
        f"export const SOURCES: {{ id: string; name?: string; url?: string; status?: string; notes?: string }}[] = {json.dumps(sources, indent=2)}\n\n"
        f"export const AUDIO_FILES_IN_REPO = {audio_files}\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)}: {len(variants)} variants, {len(rights)} rights manifests, {len(sources)} sources, {audio_files} audio files")


if __name__ == "__main__":
    main()
